name: Generate Datas

on:
  push:
    branches:
      - main # or the default branch name of your repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        with:
          github_user_name: dmenezessousa
          github_repo_name: dmenezessousa
          svg_out_path: dist/github-contribution-grid-snake.svg
